[workspace]
resolver = "2"
members = [
    "d1_not_quite_lisp",
    "d2_i_was_told_there_would_be_no_math",
    "d3_perfectly_spherical_houses_in_a_vacuum",
    "d4_the_ideal_stocking_stuffer",
    "d5_doesnt_he_have_intern_elves_for_this", "d6_probably_a_fire_hazard",
]
